#include "types.h"
#include "user.h"
int main(){
    printf(1, "before getreadcount call \n");
    // I guess, this count I get is generated by on reads done by the os it self !!!???
    int ret = getreadcount(); 
    printf(1, "after getreadcount call ret = %d \n", ret);
    exit();
}